# HTTP server bind address to serve Proksi
bind: "0.0.0.0:9090"

# List of upstreams to proxy the request to them
upstreams:
  # main is the upstream that we are sure about its behavior and its response will be the criterion. The response of the
  # request will be the main upstream response
  main:
    address: "http://localhost:8080"
  # test is the upstream that we want to test its behavior. Its response will be compared to the main upstream response
  test:
    address: "http://localhost:8081"

# Elasticsearch storage config params
elasticsearch:
  addresses: ["elastic1", "elastic2"]
  username: ""
  password: ""