apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proksi.fullname" . }}
  labels:
    {{- include "proksi.labels" . | nindent 4 }}
data:
  config.yaml: |
    # HTTP server bind address to serve Proksi
    bind: ":{{ .Values.service.containerPort }}"

    # List of upstreams to proxy the request to them
    upstreams:
      # main is the upstream that we are sure about its behavior and its response will be the criterion. The response of the
      # request will be the main upstream response
      main:
        address: {{ .Values.upstreams.main.url | quote }}
      # test is the upstream that we want to test its behavior. Its response will be compared to the main upstream response
      test:
        address: {{ .Values.upstreams.test.url | quote }}

    # Elasticsearch storage config params
    elasticsearch:
      addresses: {{- range.Values.elasticsearch.addresses }}
        - {{.}}{{- end }}
      username: {{ .Values.elasticsearch.username | quote }}
      password: {{ .Values.elasticsearch.password | quote }}
