name: Test

on:
  push:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
      - run: make check-suite
